// priority: 1000

// Block
onEvent('block.registry', event => {
	event.create('ibpdx:neptune_dungeon_floor').material('stone').hardness(1.0).displayName('海王星地牢地板')
	event.create('ibpdx:circuit_case').material('stone').hardness(1.0).displayName('电路箱')
	event.create('ibpdx:space_glass').material('glass').hardness(1.0).displayName('太空玻璃').defaultTranslucent()
	event.create('ibpdx:terra_glass').material('glass').hardness(1.0).displayName('泰拉玻璃').defaultTranslucent()
	event.create('ibpdx:space_trophy').material('stone').hardness(1.0).displayName('太空奖杯')
	event.create('ibpdx:omni_ore').material('stone').hardness(1.0).displayName('全向矿石')
	event.create('ibpdx:ultimate_tech_block').material('stone').hardness(1.0).displayName('终极科技块')
	event.create('ibpdx:ultimate_magic_block').material('stone').hardness(1.0).displayName('终极魔力块')
	event.create('ibpdx:blockcasing_awakened').material('stone').hardness(1.0).displayName('觉醒龙机壳')
	event.create('ibpdx:blockcasing_bedrock').material('stone').hardness(1.0).displayName('基岩机壳')
	event.create('ibpdx:blockcasing_black_quartz').material('stone').hardness(1.0).displayName('焦黑石英机壳')
	event.create('ibpdx:blockcasing_duskstone').material('stone').hardness(1.0).displayName('暮光石机壳')
	event.create('ibpdx:blockcasing_elementium').material('stone').hardness(1.0).displayName('元素机壳')
	event.create('ibpdx:blockcasing_empowered_diamond').material('stone').hardness(1.0).displayName('充能钻石机壳')
	event.create('ibpdx:blockcasing_empowered_steel').material('stone').hardness(1.0).displayName('充能钢机壳')
	event.create('ibpdx:blockcasing_enderium').material('stone').hardness(1.0).displayName('末影机壳')
	event.create('ibpdx:blockcasing_livingrock').material('stone').hardness(1.0).displayName('活石机壳')
	event.create('ibpdx:blockcasing_refined_glowstone').material('stone').hardness(1.0).displayName('强化荧石机壳')
	event.create('ibpdx:blockcasing_starmetal').material('stone').hardness(1.0).displayName('星辉机壳')
    event.create('ibpdx:blockcasing_steel').material('stone').hardness(1.0).displayName('钢机壳')
    event.create('ibpdx:blockcasing_manasteel').material('stone').hardness(1.0).displayName('魔力钢机壳')
    event.create('ibpdx:blockcasing_terrasteel').material('stone').hardness(1.0).displayName('泰拉钢机壳')
	event.create('ibpdx:singular_speed_gearbox').material('stone').hardness(1.0).displayName('奇异扭曲速度齿轮箱')
	event.create('ibpdx:singular_double_gearbox').material('stone').hardness(1.0).displayName('奇异扭曲双齿轮箱')
	event.create('ibpdx:singular_power_gearbox').material('stone').hardness(1.0).displayName('奇异扭曲能量齿轮箱')
	event.create('ibpdx:simulation_core').material('stone').hardness(1.0).displayName('模拟核心')
	event.create('ibpdx:life_infused_cooler').material('stone').hardness(1.0).displayName('生命注入冷却器')
	event.create('ibpdx:circuit_shell').material('stone').hardness(1.0).displayName('电路外壳')
	event.create('ibpdx:mixed_brick_block').material('stone').hardness(1.0).displayName('混合砖块')
	event.create('ibpdx:molten_gold_casing').material('stone').hardness(1.0).displayName('溶金机壳')
	event.create('ibpdx:iron_casing').material('stone').hardness(1.0).displayName('铁机壳')
	event.create('ibpdx:speed_gearbox').material('stone').hardness(1.0).displayName('速度齿轮箱')
	event.create('ibpdx:double_gearbox').material('stone').hardness(1.0).displayName('双齿轮箱')
	event.create('ibpdx:power_gearbox').material('stone').hardness(1.0).displayName('能量齿轮箱')
	event.create('ibpdx:ethetic_quartz').material('stone').hardness(1.0).displayName('装饰用石英')
	event.create('ibpdx:duplication_core').material('stone').hardness(1.0).displayName('复制核心')
	event.create('ibpdx:stainless_steel_block').material('stone').hardness(1.0).displayName('不锈钢块')
	event.create('ibpdx:stainless_steel_casing').material('stone').hardness(1.0).displayName('不锈钢机壳')
	event.create('ibpdx:hot_cooking_plate').material('stone').hardness(1.0).displayName('热烹饪板').texture('north', 'ibpdx:block/hot_cooking_platesides').texture('south', 'ibpdx:block/hot_cooking_platesides').texture('east', 'ibpdx:block/hot_cooking_platesides').texture('west', 'ibpdx:block/hot_cooking_platesides')
	event.create('ibpdx:cool_cooking_plate').material('stone').hardness(1.0).displayName('冷烹饪板').texture('north', 'ibpdx:block/cool_cooking_platesides').texture('south', 'ibpdx:block/cool_cooking_platesides').texture('east', 'ibpdx:block/cool_cooking_platesides').texture('west', 'ibpdx:block/cool_cooking_platesides')
	event.create('ibpdx:ashen_charcoal').material('dirt').hardness(0.5).displayName('灰烬木炭')
	event.create('ibpdx:bog_earth').material('dirt').hardness(0.5).displayName('沼泽土')
	event.create('ibpdx:peat_bog').material('dirt').hardness(0.5).displayName('泥炭田')
	event.create('ibpdx:azurine_moon_stone').material('stone').hardness(1.0).displayName('蔚蓝月石')
	event.create('ibpdx:chalky_moon_stone').material('stone').hardness(1.0).displayName('白垩月石')
	event.create('ibpdx:verdant_moon_stone').material('stone').hardness(1.0).displayName('翠绿月石')
	event.create('ibpdx:carmine_moon_stone').material('stone').hardness(1.0).displayName('深红月石')
	event.create('ibpdx:ultramarine_moon_stone').material('stone').hardness(1.0).displayName('天青月石')
	event.create('ibpdx:umbral_moon_stone').material('stone').hardness(1.0).displayName('阴影月石')


})
