// priority: 1000

// Fluid
onEvent('fluid.registry', event => {
	// Default Namespace for Pyrotheum and Cryotheum, bcause Powah isn't playing nice
	event.create('molten_pyrotheum').textureThick(0xf7db3a).bucketColor(0xf7db3a).displayName('熔融烈焰')
	event.create('molten_cryotheum').textureThick(0x43f4f7).bucketColor(0x43f4f7).displayName('熔融凛冰')


	event.create('ibpdx:molten_petrotheum').textureThick(0x1a1310).bucketColor(0x1a1310).displayName('熔融地岩')
	event.create('ibpdx:molten_aerotheum').textureThick(0xc8da94).bucketColor(0xc8da94).displayName('熔融空气')
    event.create('ibpdx:iron_slurry').textureThick(0xd1d1d1).bucketColor(0xd1d1d1).displayName('铁浆')
    event.create('ibpdx:gold_slurry').textureThick(0xfcdc4c).bucketColor(0xfcdc4c).displayName('金浆')
    event.create('ibpdx:lead_slurry').textureThick(0x94a9db).bucketColor(0x94a9db).displayName('铅浆')
    event.create('ibpdx:silver_slurry').textureThick(0xe4f2f7).bucketColor(0xe4f2f7).displayName('银浆')
    event.create('ibpdx:tin_slurry').textureThick(0xacccd4).bucketColor(0xacccd4).displayName('锡浆')
    event.create('ibpdx:copper_slurry').textureThick(0xf4b434).bucketColor(0xf4b434).displayName('铜浆')
	event.create('ibpdx:fusion_waste').textureThick(0x092e08).bucketColor(0x092e08).displayName('熔融废料')
	event.create('ibpdx:empowered_oil').textureThin(0xCE3535).bucketColor(0xCE3535).displayName('充能油')
	event.create('ibpdx:crystallized_oil').textureThin(0xCE3535).bucketColor(0xCE3535).displayName('晶化油')
	event.create('ibpdx:carbonic_acid').textureThin(0x111111).bucketColor(0x111111).displayName('碳酸')
    event.create('ibpdx:molten_chromium').textureThick(0xe4f2f7).bucketColor(0xe4f2f7).displayName('熔融铬')
    event.create('ibpdx:energized_speed_potion').textureThin(0x8DD4E4).bucketColor(0x8DD4E4).displayName('充能迅捷药剂')
    event.create('ibpdx:energized_strength_potion').textureThin(0x710857).bucketColor(0x710857).displayName('充能力量药剂')
    event.create('ibpdx:energized_health_potion').textureThin(0xCB1C1C).bucketColor(0xCB1C1C).displayName('充能治疗药剂')
    event.create('ibpdx:energized_fire_resistance_potion').textureThin(0xCB6E1C).bucketColor(0xCB6E1C).displayName('充能抗火药剂')
	event.create('ibpdx:earthen_blood').textureThick(0x1a1310).bucketColor(0x1a1310).displayName('岩石血')
	event.create('ibpdx:glacial_blood').textureThick(0x43f4f7).bucketColor(0x43f4f7).displayName('霜雪血')
	event.create('ibpdx:aethen_blood').textureThick(0xc8da94).bucketColor(0xc8da94).displayName('狂风血')
	event.create('ibpdx:magical_mixture').textureThin(0xDC42FF).bucketColor(0xDC42FF).displayName('魔法混合液')
	event.create('ibpdx:cooking_oil').textureThin(0x939F46).bucketColor(0x939F46).displayName('热食用油')
	event.create('ibpdx:fake_air').textureThin(0x777777).bucketColor(0x777777).displayName('热空气液')
	event.create('ibpdx:stock').textureThin(0x999999).bucketColor(0x999999).displayName('热底汤')
	event.create('ibpdx:hot_water').textureThin(0x0022BB).bucketColor(0x0022BB).displayName('热水')
	event.create('ibpdx:milk').textureThin(0xEEEEEE).bucketColor(0xEEEEEE).displayName('热牛奶')
	event.create('ibpdx:liquid_nitric_acid').textureThin(0x748412).bucketColor(0x748412).displayName('液态硝酸')
	event.create('ibpdx:liquid_nitrous_acid').textureThin(0x5DE279).bucketColor(0x5DE279).displayName('液态亚硝酸')
	event.create('ibpdx:seed_oil').textureThin(0xC99A00).bucketColor(0xC99A00).displayName('亚麻油')
	event.create('ibpdx:molten_bedrock_crystal').textureThick(0x141414).bucketColor(0x141414).displayName('熔融基岩水晶')
	event.create('ibpdx:infinity_fluid').textureThick(0xa794be).bucketColor(0x794be).displayName('无尽流体')
	event.create('ibpdx:molten_uu_matter').textureThick(0x38203d).bucketColor(0x38203d).displayName('液体反物质')
	event.create('ibpdx:liquid_nitrogen').textureThick(0x0ac9cf).bucketColor(0x0ac9cf).displayName('液氮')
	event.create('ibpdx:fluid_infinity').textureThick(0xa992bf).bucketColor(0xa992bf).displayName('熔融无尽')
	event.create('ibpdx:molten_duskstone').textureThick(0x553e5b).bucketColor(0x553e5b).displayName('熔融暮光石')
	event.create('ibpdx:nital').textureThick(0x915959).bucketColor(0x915959).displayName('硝酸酒精溶液')
	event.create('ibpdx:concentrated_nital').textureThick(0x823939).bucketColor(0x823939).displayName('精致镍锭')
	let redstone =  event.create('thermal:redstone').displayName('不稳定红石').textureStill('thermal:block/fluids/redstone_still').textureFlowing('thermal:block/fluids/redstone_flow').bucketColor(0xe30909)
	let glowstone = event.create('thermal:glowstone').displayName('充能荧石').textureStill('thermal:block/fluids/glowstone_still').textureFlowing('thermal:block/fluids/glowstone_flow').bucketColor(0xfcee06).luminosity(15)
})
